---

- name: Install botocore
  become: yes
  pip:
    name: botocore
    extra_args: --ignore-installed

- name: Install boto3
  become: yes
  pip:
    name: boto3
    extra_args: --ignore-installed

- name: Create directory for deployed code
  file:
    path: /opt/mqperf
    state: directory
    mode: u=,g=rx,o=rwx
    owner: root
    group: ec2-user
  become: true
  become_user: root
  
- name: Copy deps artifact from S3
  aws_s3:
    bucket: "{{ s3_bucket }}"
    mode: get
    object: "jars/{{ item }}.jar"
    dest: "/opt/mqperf/{{ item }}.jar"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access }}"
    aws_secret_key: "{{ aws_secret }}"
    aws_session_token: "{{ aws_session }}"
  with_items:
    - "mqperf-assembly-deps"
    - "mqperf-assembly"
  become: true

- name: Prepare start/stop/status script
  template:
    src: mqperf.sh.j2
    dest: /opt/mqperf/mqperf.sh
    mode: u=,g=rx,o=rwx
  become: true
  become_user: root
  