- name: Build mqperf deps artifact
  command: sbt assemblyPackageDependency
  args:
    chdir: "{{ mqperf_sources_dir }}"
    creates: "{{ mqperf_deps_artifact_path }}"
  delegate_to: 127.0.0.1
  register: deps_assembly

- name: Build mqperf artifact
  command: sbt assembly
  args:
    chdir: "{{ mqperf_sources_dir }}"
    creates: "{{ mqperf_artifact_path }}"
  delegate_to: 127.0.0.1
  register: assembly

- name: Create S3 bucket
  # Note a forbidden error may be due to name not being unique 
  amazon.aws.s3_bucket:
    name: "{{ s3_bucket }}"
    state: present
    region: "{{ aws_region }}"
  delegate_to: 127.0.0.1

- name: Upload deps artifact to S3
  amazon.aws.s3_object:
    bucket: "{{ s3_bucket }}"
    mode: put
    overwrite: different
    object: jars/mqperf-assembly-deps.jar
    src: "{{ mqperf_deps_artifact_path }}"
    region: "{{ aws_region }}"
  delegate_to: 127.0.0.1
  
- name: Upload artifact to S3
  amazon.aws.s3_object:
    bucket: "{{ s3_bucket }}"
    mode: put
    object: jars/mqperf-assembly.jar
    overwrite: different
    src: "{{ mqperf_artifact_path }}"
    region: "{{ aws_region }}"
  delegate_to: 127.0.0.1

