---
- import_tasks: stop.yml
  when: run_mode == 'Stop'

- import_tasks: prepare_storage.yml
  when: storage_device is defined

- import_tasks: install.yml
  when: not skip_install and ( run_mode == 'Install' or run_mode == 'Deploy' )

- import_tasks: configure.yml
  when: run_mode == 'Configure' or run_mode == 'Deploy'

- import_tasks: start.yml
  when: run_mode == 'Start' or run_mode == 'Deploy'
