---
mqperf_version: "3.0"
mqperf_artifact_path: "{{ mqperf_sources_dir }}/target/scala-2.12/mqperf-assembly-{{ mqperf_version }}.jar"
mqperf_deps_artifact_path: "{{ mqperf_sources_dir }}/target/scala-2.12/mqperf-assembly-{{ mqperf_version }}-deps.jar"
