---
- hosts: localhost
  connection: local
  gather_facts: False

  environment:
    AWS_REGION: "{{ aws_region }}"

  tasks:
  - name: Delete S3 bucket
    amazon.aws.s3_bucket:
      name: "{{ s3_bucket }}"
      state: absent
      force: true
