---
- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 3, ec2_groups: [ 'mqperf_ssh_access', 'default'], aws_instance_type: "{{ ec2_instance_type }}", ec2_tag_group: Kafka, volume_size: 100 }

- hosts: Kafka
  become: true
  roles:
  - role: java
  - role: zookeeper
    tags: ['zookeeper']
  - role: kafka
    tags: ['kafka']
