---
- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 1, ec2_groups: [ 'mqperf_ssh_access', 'mqperf_grafana_access', 'mqperf_prometheus_access', 'default'], aws_instance_type: m5.large, ec2_tag_group: Prometheus, volume_size: 100 }

- hosts: Prometheus
  become: true
  roles:
  - role: python
  - role: prometheus_grafana
