---
- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 3, ec2_groups: [ 'mqperf_ssh_access', 'default', 'mqperf_rabbitmq_access' ], aws_instance_type: t2.small, ec2_tag_group: Rabbitmq }

- hosts: Rabbitmq
  become: true
  roles:
    - role: rabbitmq
      tags: ['rabbitmq']
