---
- hosts: 127.0.0.1
  connection: local
  roles:
  - role: aws_common
  - { role: ec2_instance, count: 6, ec2_groups: ['mqperf_ssh_access', 'default', 'mqperf_activemq_artemis_access'], aws_instance_type: t2.small, ec2_tag_group: Artemis}
  
- hosts: Artemis
  become: true
  roles:
  - role: java
  - role: artemis
