---
- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 7, ec2_groups: ['mqperf_ssh_access', 'default', 'mqperf_rocketmq_access'], aws_instance_type: r5.2xlarge, ec2_tag_group: Rocketmq, volume_size: 100 }

- hosts: Rocketmq
  become: true
  roles:
  - role: maven
  - role: rocketmq
