---

- hosts: 127.0.0.1
  connection: local
  roles:
  - role: scala
  - role: aws_common
  - { role: ec2_instance, count: 4, ec2_groups: [ 'mqperf_ssh_access', 'default' ], aws_instance_type: "{{ ec2_instance_type }}", ec2_tag_group: Receiver }

- hosts: Receiver
  roles:
  - role: java
  - role: python
  - role: mqperf_receiver

- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 2, ec2_groups: [ 'mqperf_ssh_access', 'default' ], aws_instance_type: "{{ ec2_instance_type }}", ec2_tag_group: Sender }

- hosts: Sender
  roles:
  - role: java
  - role: python
  - role: mqperf_sender
