- name: Provision a set of instances
  ec2_instance:
    key_name: "{{ key_name }}"
    instance_type: "{{ aws_instance_type }}"
    image_id: "{{ aws_ami_id }}"
    vpc_subnet_id: "{{ subnet_external }}"
    region: "{{ aws_region }}"
    wait: true
    name: "{{ ec2_tag_group.lower() }}"
    network:
      assign_public_ip: "{{ use_private_addresses == false }}"
    security_groups: "{{ ec2_groups }}"
    tags:
      group: "{{ ec2_tag_group }}"
      kind: "mqperf-instance"
    state: running
    exact_count: "{{ count }}"
    filters:
      tag:group: "{{ ec2_tag_group }}"
      tag:kind: "mqperf-instance"
      instance-state-name: running
  register: ec2

- name: Wait for ssh to come up
  wait_for: host="{% if use_private_addresses|bool %}{{ item.private_dns_name }}{% else %}{{ item.public_dns_name }}{% endif %}" port=22 delay=10 timeout=300
  with_items: "{{ ec2.instances }}"
  when: ec2.changed

- name: Provision and attach EBS volume
  ec2_vol:
    instance: "{{ item.instance_id }}"
    region: "{{ aws_region }}"
    zone: "{{ aws_zone }}"
    volume_size: "{{ volume_size }}"
    volume_type: "gp2"
    delete_on_termination: yes
  with_items: "{{ ec2.instances }}"
  when: volume_size is defined and ec2.changed

- name: Refresh inventory
  meta: refresh_inventory